version: 2
jobs:
  one:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: It might work
          command: echo We did it reddit.      
  two:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Friendly Greeting
          command: echo A more familiar hi
      
workflows:
  version: 2
  one_and_two:
    jobs:
      - one
      - two
