version: 2
jobs:
  one:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - command: echo A first hello
  two:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - command: echo A more familiar hi
      
workflows:
  version: 2
  one_and_two:
    jobs:
      - one
      - two
